### PR TITLE
Removed the RxSchedulers class and replaced with the RxJavaPlugins

### PR DESCRIPTION
**Pull request by athkalia**
Removed the RxSchedulers class and replaced with the RxJavaPlugins way of overriding the Schedulers.

### CODE REVIEW

**Comment by miguelslemos** [comment]
why you removed  `throws Exception {` from test code? this issue still happen

**Comment by miguelslemos** [comment]
IOExeception still happen running Roboletric test #https://github.com/facebook/stetho/issues/440

I did an improvement for your TestUtil class
```
/**
 * Hacky way to be able to say whether which tests are running or not.
 * We are checking which one of the test classes is running in the vm.
 * If it's not loaded it means that test are not running.
 */
@ForTestingPurposes

public final class TestUtil {

    private TestUtil() {
        throw new AssertionError();
    }
 
    public static boolean areEspressoTestsRunning() {
        boolean testsAreRunning = false;
        try {
            Class.forName("com.example.util.EspressoTestRunner");
            testsAreRunning = true;
        } catch (ClassNotFoundException e) {
            testsAreRunning = false;
        }
        return testsAreRunning;
    }

    public static boolean areUnitTestRunning() {
        boolean jUnitAreRunning = false;
        try {
            Class.forName("com.example.util.PreconfiguredRobolectricTestRunner");
            jUnitAreRunning = true;
        } catch (ClassNotFoundException e) {
            jUnitAreRunning = false;
        }
        return jUnitAreRunning;
    }

}

```

and at App.java

```
    private void initStetho() {
        if (!TestUtil.areUnitTestRunning()) {
            stethoTool.init();
        }
    }
```

**Comment by athkalia** [comment]
Thanks for the suggestion. 
Next time please open a new issue, as I almost didn't see this : >

Would you like to make a PR for this @miguelslemos  or shall I make one myself?

**Comment by athkalia** [comment]
Making one myself, should be in develop in a few days. Thanks again for the suggestion

**Pull request merged**
